### ISSUE TITLE
Map becomes unusable when zooming and changing the orientation at the same time

### ISSUE THREAD

**Issue by billie80** [andreynovikov/trekarta#184]
This is really hard to explain. Under some conditions, I think when zooming and changing the orientation at the same time no map is displayed anymore. Zoom level is at 10000 km and only a blank view is displayed.
The only way to make the App usable again is deleting the App data.

**Comment by andreynovikov** [comment]
Have never met this. Will think how to fix that.

**Comment by billie80** [comment]
Thanks for looking at it.
Actually I experience it rather often.
If you need anything which could help solving this just ask.

**Comment by andreynovikov** [comment]
Please enable zoom buttons in Settings. Next time it will happen will zoom button let you zoom in?

**Comment by billie80** [comment]
Tried this now. The zoom buttons don't allow me to zoom in if it happens.

**Comment by billie80** [comment]
I think I can reliably reproduce it by switching between portrait and landscape orientation while at the same time zooming in and out! Please see the screencast below. I have enabled taps so the zoom actions are visible.

https://user-images.githubusercontent.com/9938306/165391077-e4772f90-4cee-4c80-b583-28fe4fd8f2b2.mp4

**Comment by heyheyhello** [comment]
@billie80 What version? I installed 2022.04 today and can't reproduce it. It seems the default Android 12 screenrecorder doesn't show finger location unfortunately, but trust that I'm trying my best to zoom and orient at the same time.

In my case it seems that Trekarta doesn't perform the reorientation until _after_ I've released my fingers. If I keep them on the screen it'll lock screen rotation despite me physically rotating the phone. It only rotates with no fingers on it. Maybe this is an Android 12 thing?

https://user-images.githubusercontent.com/44614862/165435971-0f34048c-0bb7-47fa-a191-ce8fc97ef6f8.mp4

**Comment by heyheyhello** [comment]
Tested with 4 different apps - it seems it's Android that's blocking the rotation until fingers are released from the screen. I guess this means the bug isn't possible to reproduce for this OS version :/

**Comment by billie80** [comment]
Still on 2021.04. Waiting for F-Droid to pick up the new version. It builds from source and checks for new tags on GitHub but it seems the new version was released to the Play Store before there was a GitHub tag. It will be in the next build cycle. If it successfully builds, maybe I can test it in a few days.
@andreynovikov Any chance to create the tag earlier?
I am on Android 10.
I enabled the finger taps in the developer options. Maybe this is possible on Android 12 as well.
It is not perfectly visible in my video but I think rotating an zooming do not happen simultaneously. It just happens in a quick sequence. As you say if I zoom and keep the fingers on the screen, orientation does not change when I rotate the phone. This only happens after the fingers are released.

**Comment by andreynovikov** [comment]
Yes, I forgot to tag last release, figured it out several days after.

**Comment by billie80** [comment]
Just want to let you know that it still happens with version 2022.04.

**Comment by heyheyhello** [comment]
@billie80 have you been able to reproduce it on more than one Android device? I've tried on 3 devices (Pixel 5a, Essential PH1, and LG K20) and cannot reproduce yet :/

**Comment by tomate44** [comment]
Hello,
This bug happened to me twice also.
I am using a Gigaset GS290, running [/e/OS](https://e.foundation/e-os/), based on Android 10.
Trekarta version is 2021.04, from F-droid.
Zoom buttons didn't fix the bug.
BTW, thanks a lot for this app, I really love it.

**Comment by billie80** [comment]
@heyheyhello unfortunately I don't have other devices to test at the moment.
@tomate44 thanks for confirming this on another device.
I also run Android 10 without GMS but don't think this is the reason.
I have access to the same device as mine with GMS. I can try there to make sure.
